name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc, clang]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4


    - name: Update submodules
      run: git submodule update --init --recursive


    - name: Create directories
      run: |
        mkdir -p ${{ github.workspace }}/bin
        mkdir -p ${{ github.workspace }}/build

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=${{ github.workspace }}/bin
      shell: bash
      
    - name: Build
      run: |
        cd ${{ github.workspace }}/build
        cmake --build ${{ github.workspace }}/build --config ${{ matrix.build_type }}
